[build]
command = "composer install --no-interaction --prefer-dist --no-dev --no-scripts --ignore-platform-reqs && php artisan package:discover --ansi && npm run build"
publish = "dist"

[build.environment]
PHP_VERSION = "8.3"
